## PyTorch Pipline using NN Module

### Perceptron

In [1]:
import torch
import torch.nn as nn

In [2]:
#architecture of neural network

class Model(nn.Module):
    
    def __init__(self, num_features):
        
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid=nn.Sigmoid()
#forward pass

    def forward(self, features):
        out=self.linear(features)
        out=self.sigmoid(out)
        return out

In [3]:
#synthetic dataset

features=torch.rand(10,5)

#create model
model=Model(features.shape[1])

#call model for forward pass
model(features)

tensor([[0.5885],
        [0.6510],
        [0.5817],
        [0.5698],
        [0.5767],
        [0.6392],
        [0.5869],
        [0.5162],
        [0.5196],
        [0.4979]], grad_fn=<SigmoidBackward0>)

In [4]:
model.linear.weight

Parameter containing:
tensor([[-0.4105, -0.0976,  0.0098, -0.0622,  0.3508]], requires_grad=True)

In [5]:
model.linear.bias

Parameter containing:
tensor([0.3994], requires_grad=True)

In [6]:
from torchinfo import summary

In [7]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## NN with 5 input and 1 hidden layer

In [8]:
class Model(nn.Module):
    def __init__(self, num_features):
        
        super().__init__()
        self.linear1=nn.Linear(num_features,3)
        self.relu=nn.ReLU()
        self.linear2=nn.Linear(3,1)
        self.sigmoid=nn.Sigmoid()
        
    def forward(self, features):
        out=self.linear1(features)
        out=self.relu(out)
        out=self.linear2(out)
        out=self.sigmoid(out)
        return out

In [9]:
# create dataset

features= torch.rand(10,5)

#create model
model=Model(features.shape[1])

#call model for forward pass
model(features)

tensor([[0.3543],
        [0.3570],
        [0.3592],
        [0.3535],
        [0.3571],
        [0.3598],
        [0.3558],
        [0.3505],
        [0.3557],
        [0.3581]], grad_fn=<SigmoidBackward0>)

In [10]:
model.linear1.weight

Parameter containing:
tensor([[-0.0425,  0.2430, -0.2809,  0.0144, -0.2687],
        [-0.1178, -0.2944, -0.1054, -0.2946, -0.1333],
        [ 0.2496, -0.1696,  0.3829, -0.1966,  0.1904]], requires_grad=True)

In [11]:
model.linear2.weight

Parameter containing:
tensor([[-0.5031, -0.2692, -0.0817]], requires_grad=True)

In [12]:
model.linear1.bias

Parameter containing:
tensor([-0.0329, -0.2401,  0.2191], requires_grad=True)

In [13]:
model.linear2.bias

Parameter containing:
tensor([-0.5560], requires_grad=True)

In [14]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Sequential Container


In [15]:
class Model(nn.Module):
    def __init__(self, num_features):
        
        super().__init__()
        self.network= nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid())
        
    def forward(self,features):
        out=self.network(features)
        return out

In [16]:
# create dataset

features= torch.rand(10,5)

#create model
model=Model(features.shape[1])

#call model for forward pass
model(features)

tensor([[0.5565],
        [0.5563],
        [0.5725],
        [0.5789],
        [0.5565],
        [0.5640],
        [0.5587],
        [0.5759],
        [0.5561],
        [0.5480]], grad_fn=<SigmoidBackward0>)